import { Rate } from "antd";
import Head from "next/head";
import Link from "next/link";
import styles from '../styles/Home.module.css'
import { Menu, Dropdown, message, Modal, Button } from 'antd';
import AddShop from '../comps/addForms/addShop'
import { useState } from "react";
import {PlusOutlined} from '@ant-design/icons'
import ShopsContainer from "../comps/market-cards/shopsContainer";

export async function getStaticProps() {
  const res = await fetch(
    "http://192.168.1.114:8080/nazin/shops"
  );
  const shops = await res.json();
  return {
    props: { shops },
  };
}

export default function Home({shops}) {

  const [isModalVisible, setIsModalVisible] = useState(false);
  const showModal = () => {
    setIsModalVisible(true);
  };
  const handleCancel = () => {
    setIsModalVisible(false);
  };


  return (
    <div className={styles.page}>
      <div className={styles.container}>
        <Head>
          <title>Shopping Center</title>
          <meta name="description" content="Generated by Naarin" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.technoMarketCard}>
          <Link href='/shops/technoMarket/'><a>Techno Market</a></Link>
        </div>
        <ShopsContainer shops={shops}/>
      </div>
      <footer className={styles.footer} >
      
        <div
          style={{
            width: "150px",
            height: "60px",
            textAlign: "center",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            padding: "5px",
            fontSize:"15px",
            flexDirection:"column"
          }}
          onClick={showModal}
        >
          <PlusOutlined  style={{fontSize:"30px" , marginBottom:"5px"}}/>
          Add Shop
        </div>

        <Modal onCancel={handleCancel} visible={isModalVisible} footer="">
          <AddShop />
        </Modal>
      </footer>
    </div>
  );
}
